// Auto-generated by NLS Refactor. Do not edit manually.
const { translate } = require('./nls_loader');

const nls_ts = {
  nlsService: {
    key: {
      create: {
        collision: {
          message: "nlsService.key.create.collision.message"
        },
        input: {
          prompt: {
            typedef: "nlsService.key.create.input.prompt.typedef",
            string: "nlsService.key.create.input.prompt.string",
            title: "nlsService.key.create.input.prompt.title"
          }
        },
        firsttime: {
          info: {
            title: "nlsService.key.create.firsttime.info.title",
            yes: "nlsService.key.create.firsttime.info.yes",
            cancel: "nlsService.key.create.firsttime.info.cancel"
          }
        },
        editorfocuschanged: {
          warning: "nlsService.key.create.editorfocuschanged.warning"
        },
        info: {
          success: "nlsService.key.create.info.success"
        },
        error: {
          critical: "nlsService.key.create.error.critical",
          workspacenotfound: "nlsService.key.create.error.workspacenotfound"
        },
        warning: {
          notinserted: "nlsService.key.create.warning.notinserted"
        }
      }
    }
  },
  nls: {
    action: {
      string: {
        title: "nls.action.string.title"
      },
      typedef: {
        title: "nls.action.typedef.title"
      }
    },
    command: {
      string: {
        title: "nls.command.string.title"
      },
      typedef: {
        title: "nls.command.typedef.title"
      }
    }
  }
};

module.exports = { nls_ts, translate };